export const MAGIC_BRUSH_IDLE_TIME = 500;
export const MAGIC_BRUSH_TRAIL_COLOR = '#84cfff66';
export const MAGIC_BRUSH_TRAIL_WIDTH = 10;
export const MAGIC_BRUSH_MIN_BOUND_SIZE = 24;
export const MAGIC_BRUSH_MIN_PATH_LENGTH = 48;
export const MAGIC_BRUSH_MIN_SCORE = 0.32;
